import json
import urllib.error
import urllib.request

from maca import maca_config as config


class ClaudeClient:
    def __init__(self):
        self.api_key = config.get_claude_api_key()
        self.model = config.CLAUDE_MODEL
        self.timeout = config.CLAUDE_TIMEOUT_SECONDS

    def generate(self, prompt, system_instruction=""):
        if not self.api_key:
            if config.MOCK_GEMMA_FALLBACK:
                return self._generate_mock(prompt, system_instruction)
            raise ValueError("CLAUDE_API_KEY is not set.")

        url = "https://api.anthropic.com/v1/messages"

        payload = {
            "model": self.model,
            "max_tokens": 4096,
            "messages": [{"role": "user", "content": prompt}],
        }

        if system_instruction:
            payload["system"] = system_instruction

        headers = {
            "Content-Type": "application/json",
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
        }

        # Setup secure SSL context using certifi if available
        import ssl

        try:
            import certifi

            ssl_context = ssl.create_default_context(cafile=certifi.where())
        except ImportError:
            ssl_context = ssl.create_default_context()

        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers=headers,
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=self.timeout, context=ssl_context) as response:
                res = json.loads(response.read().decode("utf-8"))
                # Extract response text from the Messages API response
                content_blocks = res.get("content", [])
                if content_blocks:
                    # Concatenate all text blocks
                    texts = [
                        block.get("text", "")
                        for block in content_blocks
                        if block.get("type") == "text"
                    ]
                    if texts:
                        return "\n".join(texts)
                return "Error: Empty response from Claude."
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8")
            try:
                err_json = json.loads(error_body)
                msg = err_json.get("error", {}).get("message", error_body)
                err_type = err_json.get("error", {}).get("type", "")
                err_msg = f"{err_type}: {msg}"
            except Exception:
                err_msg = error_body
            if config.MOCK_GEMMA_FALLBACK:
                return self._generate_mock(prompt, system_instruction)
            raise RuntimeError(f"Claude API request failed (HTTP {e.code}): {err_msg}")
        except Exception as e:
            if config.MOCK_GEMMA_FALLBACK:
                return self._generate_mock(prompt, system_instruction)
            raise RuntimeError(f"Claude API request failed: {e}")

    def _generate_mock(self, prompt, system_instruction):
        # prompt_lower = prompt.lower()
        sys_lower = system_instruction.lower()

        if "coder" in sys_lower:
            return """[FILE: output_claude.py]
```python
# Generated by Claude Agent (Mocked)
import urllib.request
import json


def fetch_url(url):
    print(f"Fetching: {url}")
    try:
        with urllib.request.urlopen(url) as res:
            return res.read().decode("utf-8")
    except Exception as e:
        return f"Error: {e}"


if __name__ == "__main__":
    content = fetch_url("https://httpbin.org/get")
    print(content[:200])
```"""
        elif "reviewer" in sys_lower:
            return """# Code Review (Claude Mocked)
- Syntax checks: PASSED
APPROVED."""
        else:
            return """# Implementation Plan (Claude Mocked)
1. [NEW] Create `output_claude.py` with advanced network utility logic.
2. Verify connection.
"""
