import json
import urllib.request
import urllib.error
from maca import maca_config as config

class GeminiClient:
    def __init__(self):
        self.api_key = config.get_gemini_api_key()
        self.model = "gemini-3.5-flash"

    def generate(self, prompt, system_instruction=""):
        if not self.api_key:
            if config.MOCK_GEMMA_FALLBACK:
                return self._generate_mock(prompt, system_instruction)
            raise ValueError("GEMINI_API_KEY is not set.")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"
        
        payload = {
            "contents": [{
                "parts": [{"text": prompt}]
            }]
        }
        
        if system_instruction:
            payload["systemInstruction"] = {
                "parts": [{"text": system_instruction}]
            }

        # Setup secure SSL context using certifi if available
        import ssl
        try:
            import certifi
            ssl_context = ssl.create_default_context(cafile=certifi.where())
        except ImportError:
            ssl_context = ssl.create_default_context()

        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST"
            )
            with urllib.request.urlopen(req, timeout=45, context=ssl_context) as response:
                res = json.loads(response.read().decode("utf-8"))
                # Extract response text
                candidates = res.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        return parts[0].get("text", "")
                return "Error: Empty response from Gemini."
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8")
            if config.MOCK_GEMMA_FALLBACK:
                return self._generate_mock(prompt, system_instruction)
            raise RuntimeError(f"Gemini API request failed (HTTP {e.code}): {error_body}")
        except Exception as e:
            if config.MOCK_GEMMA_FALLBACK:
                return self._generate_mock(prompt, system_instruction)
            raise RuntimeError(f"Gemini API request failed: {e}")

    def _generate_mock(self, prompt, system_instruction):
        prompt_lower = prompt.lower()
        sys_lower = system_instruction.lower()
        
        if "coder" in sys_lower:
            return """[FILE: output_gemini.py]
```python
# Generated by Gemini Agent (Mocked)
import urllib.request
import json

def fetch_url(url):
    print(f"Fetching: {url}")
    try:
        with urllib.request.urlopen(url) as res:
            return res.read().decode("utf-8")
    except Exception as e:
        return f"Error: {e}"

if __name__ == "__main__":
    content = fetch_url("https://httpbin.org/get")
    print(content[:200])
```"""
        elif "reviewer" in sys_lower:
            return """# Code Review (Gemini Mocked)
- Syntax checks: PASSED
APPROVED."""
        else:
            return """# Implementation Plan (Gemini Mocked)
1. [NEW] Create `output_gemini.py` with advanced network utility logic.
2. Verify connection.
"""
