import json
import urllib.error
import urllib.request

from maca import maca_config as config


class LocalGemmaClient:
    def __init__(self):
        self.url = config.OLLAMA_API_URL
        self.model = config.OLLAMA_MODEL

    def generate(self, prompt, system_instruction=""):
        import subprocess

        # Combine system instruction and prompt
        full_prompt = prompt
        if system_instruction:
            full_prompt = f"{system_instruction}\\n\\nTask: {prompt}"

        # 1. Try HTTP API
        try:
            req = urllib.request.Request(
                f"{self.url}/api/generate",
                data=json.dumps(
                    {"model": self.model, "prompt": full_prompt, "stream": False}
                ).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=10) as response:
                res = json.loads(response.read().decode("utf-8"))
                return res.get("response", "")
        except Exception as e:
            # 2. Try Subprocess CLI
            try:
                # Run: ollama run model "prompt"
                # We pass prompt through stdin to avoid command line length limits
                res = subprocess.run(
                    ["ollama", "run", self.model],
                    input=full_prompt,
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                if res.returncode == 0:
                    return res.stdout.strip()
            except FileNotFoundError:
                pass
            except Exception:
                pass

            # 3. Try Mock Fallback
            if config.MOCK_GEMMA_FALLBACK:
                return self._generate_mock(prompt, system_instruction)

            raise RuntimeError(f"Failed to connect to local Gemma via Ollama API and CLI: {e}")

    def _generate_mock(self, prompt, system_instruction):
        # prompt_lower = prompt.lower()
        sys_lower = system_instruction.lower()

        if "coder" in sys_lower:
            return """[FILE: output_gemma.py]
```python
# Generated by Local Gemma Agent
def main():
    print("Hello from local Gemma agent!")

if __name__ == "__main__":
    main()
```"""
        elif "reviewer" in sys_lower:
            return """# Code Review
- Syntax check: PASSED
- Correctness check: PASSED
APPROVED."""
        else:
            return """# Implementation Plan
1. [NEW] Create `output_gemma.py` with code logic.
2. Run sanity check.
"""
